{{- if .Values.ingress.enabled }}
# Store-Front Ingress (serves from /)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aks-store-ingress
  labels:
    app.kubernetes.io/name: store-front
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: store-front
            port:
              number: 80
{{- end }}